[package]
name = "componentize"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "cordis 构建工具：将 wasip1 核心模块编码为组件模型组件（预览1 适配器）"

[lints]
workspace = true

[dependencies]
anyhow = "1"
wit-component = "0.256"
wit-parser = "0.256"
