// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     cordis:core@0.1.0

package export_cordis_core_plugin

import (
	"unsafe"
)

//go:wasmimport [export]cordis:core/plugin@0.1.0 [resource-new]task
func resourceNewTask(pointer unsafe.Pointer) int32

//go:wasmimport [export]cordis:core/plugin@0.1.0 [resource-rep]task
func resourceRepTask(handle int32) unsafe.Pointer

//go:wasmimport [export]cordis:core/plugin@0.1.0 [resource-drop]task
func resourceDropTask(handle int32)

//go:wasmexport cordis:core/plugin@0.1.0#[dtor]task
func resourceDtorTask(rep int32) {
	val := (*Task)(unsafe.Pointer(uintptr(rep)))
	val.handle = 0
	val.pinner.Unpin()
	val.OnDrop()
}

func (self *Task) TakeHandle() int32 {
	self.pinner.Pin(self)
	self.handle = resourceNewTask(unsafe.Pointer(self))
	return self.handle
}

func (self *Task) SetHandle(handle int32) {
	if self.handle != handle {
		panic("invalid handle")
	}
}

func (self *Task) Drop() {
	handle := self.handle
	if self.handle != 0 {
		self.handle = 0
		resourceDropTask(handle)
		self.pinner.Unpin()
		self.OnDrop()
	}
}

func TaskFromOwnHandle(handle int32) *Task {
	return (*Task)(unsafe.Pointer(resourceRepTask(handle)))
}

func TaskFromBorrowHandle(rep int32) *Task {
	return (*Task)(unsafe.Pointer(uintptr(rep)))
}

//go:wasmimport [export]cordis:core/plugin@0.1.0 [resource-new]component
func resourceNewComponent(pointer unsafe.Pointer) int32

//go:wasmimport [export]cordis:core/plugin@0.1.0 [resource-rep]component
func resourceRepComponent(handle int32) unsafe.Pointer

//go:wasmimport [export]cordis:core/plugin@0.1.0 [resource-drop]component
func resourceDropComponent(handle int32)

//go:wasmexport cordis:core/plugin@0.1.0#[dtor]component
func resourceDtorComponent(rep int32) {
	val := (*Component)(unsafe.Pointer(uintptr(rep)))
	val.handle = 0
	val.pinner.Unpin()
	val.OnDrop()
}

func (self *Component) TakeHandle() int32 {
	self.pinner.Pin(self)
	self.handle = resourceNewComponent(unsafe.Pointer(self))
	return self.handle
}

func (self *Component) SetHandle(handle int32) {
	if self.handle != handle {
		panic("invalid handle")
	}
}

func (self *Component) Drop() {
	handle := self.handle
	if self.handle != 0 {
		self.handle = 0
		resourceDropComponent(handle)
		self.pinner.Unpin()
		self.OnDrop()
	}
}

func ComponentFromOwnHandle(handle int32) *Component {
	return (*Component)(unsafe.Pointer(resourceRepComponent(handle)))
}

func ComponentFromBorrowHandle(rep int32) *Component {
	return (*Component)(unsafe.Pointer(uintptr(rep)))
}
