// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     cordis:core@0.1.0

package cordis_core_context

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

const (
	ValueFlag   uint8 = 0
	ValueCount  uint8 = 1
	ValueOffset uint8 = 2
	ValueText   uint8 = 3
	ValueBlob   uint8 = 4
)

// 跨边界值（v1 标量集；case 名避开 WIT 关键字）。
type Value struct {
	tag   uint8
	value any
}

func (self Value) Tag() uint8 {
	return self.tag
}

func (self Value) Flag() bool {
	if self.tag != ValueFlag {
		panic("tag mismatch")
	}
	return self.value.(bool)
}
func (self Value) Count() uint64 {
	if self.tag != ValueCount {
		panic("tag mismatch")
	}
	return self.value.(uint64)
}
func (self Value) Offset() int64 {
	if self.tag != ValueOffset {
		panic("tag mismatch")
	}
	return self.value.(int64)
}
func (self Value) Text() string {
	if self.tag != ValueText {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Value) Blob() []uint8 {
	if self.tag != ValueBlob {
		panic("tag mismatch")
	}
	return self.value.([]uint8)
}

func MakeValueFlag(value bool) Value {
	return Value{ValueFlag, value}
}
func MakeValueCount(value uint64) Value {
	return Value{ValueCount, value}
}
func MakeValueOffset(value int64) Value {
	return Value{ValueOffset, value}
}
func MakeValueText(value string) Value {
	return Value{ValueText, value}
}
func MakeValueBlob(value []uint8) Value {
	return Value{ValueBlob, value}
}

//go:wasmimport cordis:core/context@0.1.0 [resource-drop]inverse
func resourceDropInverse(handle int32)

type Inverse struct {
	handle *witRuntime.Handle
}

func (self *Inverse) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Inverse) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Inverse) Handle() int32 {
	return self.handle.Use()
}

func (self *Inverse) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropInverse(handle)
	}
}

func InverseFromOwnHandle(handleValue int32) *Inverse {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Inverse{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropInverse(handleValue)
		}
	}, 0)
	return value
}

func InverseFromBorrowHandle(handleValue int32) *Inverse {
	handle := witRuntime.MakeHandle(handleValue)
	return &Inverse{handle}
}

//go:wasmimport cordis:core/context@0.1.0 [method]inverse.run
func wasm_import_method_inverse_run(arg0 int32)

func (self *Inverse) Run() {

	wasm_import_method_inverse_run((self).Handle())

}

//go:wasmimport cordis:core/context@0.1.0 get
func wasm_import_get(arg0 uintptr, arg1 uint32, arg2 uintptr)

func Get(key string) witTypes.Option[Value] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (16 + 2*4), 8))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	wasm_import_get(uintptr(utf8), uint32(len(key)), returnArea)
	var option witTypes.Option[Value]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[Value]()
	case 1:
		var variant Value
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:

			variant = MakeValueFlag((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) != 0))

		case 1:

			variant = MakeValueCount(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16))))

		case 2:

			variant = MakeValueOffset(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 16)))

		case 3:
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = MakeValueText(value)

		case 4:
			value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			variant = MakeValueBlob(value0)

		default:
			panic("unreachable")
		}

		option = witTypes.Some[Value](variant)
	default:
		panic("unreachable")
	}
	result := option
	return result

}

//go:wasmimport cordis:core/context@0.1.0 set
func wasm_import_set(arg0 uintptr, arg1 uint32, arg2 int32, arg3 int64, arg4 uint32, arg5 uintptr)

func Set(key string, value Value) witTypes.Result[*Inverse, string] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (3 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(key))
	pinner.Pin(utf8)
	var variant int32
	var variant1 int64
	var variant2 uint32
	switch value.Tag() {
	case ValueFlag:
		payload := value.Flag()
		var result int32
		if payload {
			result = 1
		} else {
			result = 0
		}

		variant = int32(0)
		variant1 = int64(result)
		variant2 = 0

	case ValueCount:
		payload := value.Count()

		variant = int32(1)
		variant1 = int64(payload)
		variant2 = 0

	case ValueOffset:
		payload := value.Offset()

		variant = int32(2)
		variant1 = payload
		variant2 = 0

	case ValueText:
		payload := value.Text()
		utf80 := unsafe.Pointer(unsafe.StringData(payload))
		pinner.Pin(utf80)

		variant = int32(3)
		variant1 = int64(uintptr(utf80))
		variant2 = uint32(len(payload))

	case ValueBlob:
		payload := value.Blob()
		data := unsafe.Pointer(unsafe.SliceData(payload))
		pinner.Pin(data)

		variant = int32(4)
		variant1 = int64(uintptr(data))
		variant2 = uint32(len(payload))

	default:
		panic("unreachable")
	}
	wasm_import_set(uintptr(utf8), uint32(len(key)), variant, variant1, variant2, returnArea)
	var result4 witTypes.Result[*Inverse, string]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		result4 = witTypes.Ok[*Inverse, string](InverseFromOwnHandle(int32(uintptr(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))))
	case 1:
		value3 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))

		result4 = witTypes.Err[*Inverse, string](value3)
	default:
		panic("unreachable")
	}
	result5 := result4
	return result5

}
