// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     cordis:core@0.1.0

package cordis_core_remote

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/cordis_core_context"
)

type Value = cordis_core_context.Value

//go:wasmimport cordis:core/remote@0.1.0 [resource-drop]handle
func resourceDropHandle(handle int32)

type Handle struct {
	handle *witRuntime.Handle
}

func (self *Handle) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Handle) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Handle) Handle() int32 {
	return self.handle.Use()
}

func (self *Handle) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropHandle(handle)
	}
}

func HandleFromOwnHandle(handleValue int32) *Handle {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Handle{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropHandle(handleValue)
		}
	}, 0)
	return value
}

func HandleFromBorrowHandle(handleValue int32) *Handle {
	handle := witRuntime.MakeHandle(handleValue)
	return &Handle{handle}
}

//go:wasmimport cordis:core/remote@0.1.0 [method]handle.take
func wasm_import_method_handle_take(arg0 int32, arg1 uintptr)

func (self *Handle) Take() witTypes.Option[witTypes.Result[cordis_core_context.Value, string]] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (24 + 2*4), 8))
	wasm_import_method_handle_take((self).Handle(), returnArea)
	var option witTypes.Option[witTypes.Result[cordis_core_context.Value, string]]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option = witTypes.None[witTypes.Result[cordis_core_context.Value, string]]()
	case 1:
		var result witTypes.Result[cordis_core_context.Value, string]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8))) {
		case 0:
			var variant cordis_core_context.Value
			switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))) {
			case 0:

				variant = cordis_core_context.MakeValueFlag((uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))) != 0))

			case 1:

				variant = cordis_core_context.MakeValueCount(uint64(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 24))))

			case 2:

				variant = cordis_core_context.MakeValueOffset(*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), 24)))

			case 3:
				value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 1*4))))

				variant = cordis_core_context.MakeValueText(value)

			case 4:
				value0 := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 24))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 1*4))))

				variant = cordis_core_context.MakeValueBlob(value0)

			default:
				panic("unreachable")
			}

			result = witTypes.Ok[cordis_core_context.Value, string](variant)
		case 1:
			value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 16))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 1*4))))

			result = witTypes.Err[cordis_core_context.Value, string](value1)
		default:
			panic("unreachable")
		}

		option = witTypes.Some[witTypes.Result[cordis_core_context.Value, string]](result)
	default:
		panic("unreachable")
	}
	result2 := option
	return result2

}

//go:wasmimport cordis:core/remote@0.1.0 submit
func wasm_import_submit(arg0 uintptr, arg1 uint32, arg2 uintptr, arg3 uint32) int32

func Submit(name string, params []cordis_core_context.Value) *Handle {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	utf8 := unsafe.Pointer(unsafe.StringData(name))
	pinner.Pin(utf8)
	slice := params
	length := uint32(len(slice))
	result1 := witRuntime.Allocate(pinner, uintptr(length*(8+2*4)), 8)
	for index, element := range slice {
		base := unsafe.Add(result1, index*(8+2*4))

		switch element.Tag() {
		case cordis_core_context.ValueFlag:
			payload := element.Flag()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
			var result int32
			if payload {
				result = 1
			} else {
				result = 0
			}
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 8)) = int8(result)

		case cordis_core_context.ValueCount:
			payload := element.Count()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(1))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = int64(payload)

		case cordis_core_context.ValueOffset:
			payload := element.Offset()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(2))
			*(*int64)(unsafe.Add(unsafe.Pointer(base), 8)) = payload

		case cordis_core_context.ValueText:
			payload := element.Text()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(3))
			utf80 := unsafe.Pointer(unsafe.StringData(payload))
			pinner.Pin(utf80)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(utf80)))

		case cordis_core_context.ValueBlob:
			payload := element.Blob()
			*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(4))
			data := unsafe.Pointer(unsafe.SliceData(payload))
			pinner.Pin(data)
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))) = uint32(uint32(len(payload)))
			*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)) = uint32(uintptr(uintptr(data)))

		default:
			panic("unreachable")
		}

	}

	result2 := wasm_import_submit(uintptr(utf8), uint32(len(name)), uintptr(result1), length)
	return HandleFromOwnHandle(int32(uintptr(result2)))

}
