// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     cordis:core@0.1.0

package main

import (
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
	"wit_component/export_cordis_core_plugin"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(witRuntime.Allocate(&staticPinner, (8 + 1*4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport cordis:core/plugin@0.1.0#[method]task.step
func wasm_export_cordis_core_plugin_method_task_step(arg0 uintptr) uintptr {

	result := (export_cordis_core_plugin.TaskFromBorrowHandle(int32(uintptr(arg0)))).Step()

	switch result.Tag() {
	case witTypes.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case witTypes.OptionSome:
		payload := result.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		*(*int32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = ((payload).Inverse).TakeHandle()
		var result0 int32
		if (payload).Done {
			result0 = 1
		} else {
			result0 = 0
		}
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 8)) = int8(result0)

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cordis:core/plugin@0.1.0#[constructor]component
func wasm_export_cordis_core_plugin_constructor_component() int32 {

	result := export_cordis_core_plugin.MakeComponent()
	return (result).TakeHandle()

}

//go:wasmexport cordis:core/plugin@0.1.0#[method]component.inject
func wasm_export_cordis_core_plugin_method_component_inject(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_cordis_core_plugin.ComponentFromBorrowHandle(int32(uintptr(arg0)))).Inject()
	slice := result
	length := uint32(len(slice))
	result0 := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result0, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(result0)))
	return exportReturnArea

}

//go:wasmexport cabi_post_cordis:core/plugin@0.1.0#[method]component.inject
func wasm_export_post_return_cordis_core_plugin_method_component_inject(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport cordis:core/plugin@0.1.0#[method]component.provide
func wasm_export_cordis_core_plugin_method_component_provide(arg0 uintptr) uintptr {

	pinner := &syncExportPinner
	result := (export_cordis_core_plugin.ComponentFromBorrowHandle(int32(uintptr(arg0)))).Provide()
	slice := result
	length := uint32(len(slice))
	result0 := witRuntime.Allocate(pinner, uintptr(length*(2*4)), 4)
	for index, element := range slice {
		base := unsafe.Add(result0, index*(2*4))
		utf8 := unsafe.Pointer(unsafe.StringData(element))
		pinner.Pin(utf8)
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uint32(len(element)))
		*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)) = uint32(uintptr(uintptr(utf8)))

	}

	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(length)
	*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = uint32(uintptr(uintptr(result0)))
	return exportReturnArea

}

//go:wasmexport cabi_post_cordis:core/plugin@0.1.0#[method]component.provide
func wasm_export_post_return_cordis_core_plugin_method_component_provide(result uintptr) {
	syncExportPinner.Unpin()
}

//go:wasmexport cordis:core/plugin@0.1.0#[method]component.start
func wasm_export_cordis_core_plugin_method_component_start(arg0 uintptr) int32 {

	result := (export_cordis_core_plugin.ComponentFromBorrowHandle(int32(uintptr(arg0)))).Start()
	return (result).TakeHandle()

}

// Unused, but present to make the compiler happy
func main() {}
