// Generated by `wit-bindgen` 0.60.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     cordis:core@0.1.0

package cordis_core_plugin

import (
	"wit_component/cordis_core_context"
)

type Inverse = cordis_core_context.Inverse

type EffectStep struct {
	Inverse *cordis_core_context.Inverse
	Done    bool
}
